name: arre_frontend_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 5.2.6+206

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  tuple: ^2.0.2
  video_player: ^2.7.0
  package_info_plus: ^4.0.2
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.1
  flutter_riverpod: ^2.3.6
  graphql_flutter: ^5.1.2
  gql_exec: ^1.0.0
  gql: ^1.0.0
  shared_preferences: ^2.0.17
  file_picker: ^5.3.2
  image_cropper: ^5.0.0
  device_info_plus: ^9.0.2
  path_provider: ^2.0.15
  open_filex: ^4.3.2
  mime: ^1.0.4
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  http: ^1.1.0
  permission_handler: ^10.4.3
  app_tracking_transparency: ^2.0.4
  record: ^4.4.4
  fluttertoast: ^8.2.2
  flutter_localization: ^0.2.0
  intl: any
  audioplayers: ^5.2.0
  audio_service: ^0.18.12
  flutter_switch: ^0.3.2
  scrollable_positioned_list: ^0.3.8
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.27.2
  firebase_crashlytics: ^3.4.20
  firebase_messaging: ^14.7.21
  firebase_dynamic_links: ^5.4.19
  firebase_analytics: ^10.9.0
  firebase_auth: ^4.18.0
  firebase_performance: ^0.9.3+19
  firebase_remote_config: ^4.3.19
  singular_flutter_sdk: 1.2.1
  facebook_app_events: ^0.19.1
  flutter_facebook_app_links: ^3.0.2
  file_selector: ^1.0.0
  flutter_local_notifications: ^15.1.0+1
  webview_flutter: ^4.2.2
  flutter_svg: ^2.0.7
  #  lottie: ^2.4.0
  rive: ^0.11.8
  ffmpeg_kit_flutter: ^6.0.3
  url_launcher: ^6.2.1
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  share_plus: ^7.0.2
  expandable_text: ^2.3.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  built_collection: ^5.1.1
  upgrader: ^8.0.0
  version: ^3.0.2
  easy_debounce: ^2.0.3
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  dio: ^5.3.3
  open_file_manager: ^0.0.4
  in_app_review: ^2.0.8
  in_app_update: ^4.2.2
  socket_io_client: ^2.0.3+1
  recase: ^4.1.0
  flutter_card_swiper: ^7.0.0
  animated_text_kit: ^4.2.2
  markup_text: ^1.0.4

  #  Arre GraphQL services
  arre_base_gql:
    path: arre_gql_services/arre_base_gql
  arre_referral_gql:
    path: arre_gql_services/arre_referral_gql
  arre_user_manage_gql:
    path: arre_gql_services/arre_user_manage_gql
  arre_post_manage_gql:
    path: arre_gql_services/arre_post_manage_gql
  arre_user_feed_gql:
    path: arre_gql_services/arre_user_feed_gql
  arre_notification_gql:
    path: arre_gql_services/arre_notification_gql
  arre_playlist_gql:
    path: arre_gql_services/arre_playlist_gql
  arre_user_graph_gql:
    path: arre_gql_services/arre_user_graph_gql
  arre_search_service_gql:
    path: arre_gql_services/arre_search_service_gql
  arre_creator_analytics_gql:
    path: arre_gql_services/arre_creator_analytics_gql
  arre_direct_messages_gql:
    path: arre_gql_services/arre_direct_messages_gql
  arre_community_manage_gql:
    path: arre_gql_services/arre_community_manage_gql

#Added this for iOS
image_picker:
  git:
    url: https://github.com/cpboyd/plugins.git
    ref: ios-no-permissions
    path: packages/image_picker/image_picker

dependency_overrides:
  analyzer: ^6.0.0
  collection: ^1.17.2
  visibility_detector: ^0.4.0+2
  connectivity_plus: ^5.0.2
  firebase_auth_platform_interface: ^7.2.0
  firebase_core: ^2.27.2
  firebase_core_platform_interface: ^5.0.0
  ferry: ^0.14.2+1

  # flutter_math_fork: ^0.5.0
  # provider: ^6.0.2

#  ffmpeg_kit_flutter:
#    path: ./ffmpeg-kit/flutter/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  gql_code_builder: ^0.7.2
  isar_generator: ^3.1.0+1
  logger: ^2.0.2+1
#  dart_code_metrics: ^4.12.0
#  ferry_generator: ^0.8.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/animations/
    - assets/svg/floating_action_button/
    - assets/docs/privacy_policy.txt
    - assets/docs/terms_conditions.txt
    - assets/docs/community_code_conduct.txt
    - assets/models/ssd_mobilenet.tflite
    - assets/models/ssd_mobilenet.txt
    #   - images/a_dot_ham.jpe

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ArreV2
      fonts:
        - asset: assets/icons/ArreV2.ttf
    - family: ManRope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
    #         style: italic

    - family: Hind
      fonts:
        - asset: assets/fonts/Hind/Hind-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hind/Hind-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hind/Hind-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hind/Hind-Regular.ttf
          weight: 400

    - family: Acumin Pro
      fonts:
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Regular.ttf
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Light.ttf
          weight: 300
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Semibold.ttf
          weight: 600
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Black.ttf
          weight: 800
        - asset: assets/fonts/acumin_pro/Acumin-Pro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Bold.ttf
          weight: 700

    - family: ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700

    - family: Ubuntu_Mono
      fonts:
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu_Mono/UbuntuMono-Bold.ttf
          weight: 700

    # - family: poppins
    #   fonts:
    #     - asset: assets/fonts/poppins/Poppins-Regular.ttf
    #       weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
