targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: arre_user_graph_gql|lib/src/user_graph_schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: arre_user_graph_gql|lib/src/user_graph_schema.graphql

#RUN dart run build_runner build