// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:arre_post_manage_gql/src/__generated__/post_manage_queries.data.gql.dart'
    show
        GAudioInsertablesData,
        GAudioInsertablesData_response,
        GAudioInsertablesData_response_data,
        GBgMusicData,
        GBgMusicData_response,
        GBgMusicData_response_data,
        GCreateVoicepodData,
        GCreateVoicepodData_response,
        GCreateVoicepodData_response_data,
        GDeleteVoicepodData,
        GDeleteVoicepodData_response,
        GGetLanguagesData,
        GGetLanguagesData_response,
        GGetLanguagesData_response_data,
        GGetVoicepodDetailsData,
        GGetVoicepodDetailsData_response,
        GGetVoicepodDetailsData_response_data,
        GLanguageData,
        GMarkAsPlayedData,
        GMarkAsPlayedData_response,
        GMarkAsViewedData,
        GMarkAsViewedData_response,
        GPostCommentData,
        GPostCommentData_response,
        GPostCommentData_response_data,
        GPostCommentReplyData,
        GPostCommentReplyData_response,
        GPostCommentReplyData_response_data,
        GPostDetailsData,
        GUserVoicepodsData,
        GUserVoicepodsData_response,
        GUserVoicepodsData_response_data,
        GUserVoicepodsData_response_data_lastEvaluatedKey,
        GVPCommentData,
        GVPCommentReplyData,
        GVoiceEffectsData,
        GVoiceEffectsData_response,
        GVoiceEffectsData_response_data;
import 'package:arre_post_manage_gql/src/__generated__/post_manage_queries.req.gql.dart'
    show
        GAudioInsertablesReq,
        GBgMusicReq,
        GCreateVoicepodReq,
        GDeleteVoicepodReq,
        GGetLanguagesReq,
        GGetVoicepodDetailsReq,
        GLanguageReq,
        GMarkAsPlayedReq,
        GMarkAsViewedReq,
        GPostCommentReplyReq,
        GPostCommentReq,
        GPostDetailsReq,
        GUserVoicepodsReq,
        GVPCommentReplyReq,
        GVPCommentReq,
        GVoiceEffectsReq;
import 'package:arre_post_manage_gql/src/__generated__/post_manage_queries.var.gql.dart'
    show
        GAudioInsertablesVars,
        GBgMusicVars,
        GCreateVoicepodVars,
        GDeleteVoicepodVars,
        GGetLanguagesVars,
        GGetVoicepodDetailsVars,
        GLanguageVars,
        GMarkAsPlayedVars,
        GMarkAsViewedVars,
        GPostCommentReplyVars,
        GPostCommentVars,
        GPostDetailsVars,
        GUserVoicepodsVars,
        GVPCommentReplyVars,
        GVPCommentVars,
        GVoiceEffectsVars;
import 'package:arre_post_manage_gql/src/__generated__/post_manage_schema.schema.gql.dart'
    show
        GPostStatus,
        GPostVisibility,
        GlastEvaluatedKeyForReplyComments,
        GlastEvaluatedKeyForVoicepodComments,
        GlastEvaluatedKeyForVoicepods;
import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GAudioInsertablesData,
  GAudioInsertablesData_response,
  GAudioInsertablesData_response_data,
  GAudioInsertablesReq,
  GAudioInsertablesVars,
  GBgMusicData,
  GBgMusicData_response,
  GBgMusicData_response_data,
  GBgMusicReq,
  GBgMusicVars,
  GCreateVoicepodData,
  GCreateVoicepodData_response,
  GCreateVoicepodData_response_data,
  GCreateVoicepodReq,
  GCreateVoicepodVars,
  GDeleteVoicepodData,
  GDeleteVoicepodData_response,
  GDeleteVoicepodReq,
  GDeleteVoicepodVars,
  GGetLanguagesData,
  GGetLanguagesData_response,
  GGetLanguagesData_response_data,
  GGetLanguagesReq,
  GGetLanguagesVars,
  GGetVoicepodDetailsData,
  GGetVoicepodDetailsData_response,
  GGetVoicepodDetailsData_response_data,
  GGetVoicepodDetailsReq,
  GGetVoicepodDetailsVars,
  GLanguageData,
  GLanguageReq,
  GLanguageVars,
  GMarkAsPlayedData,
  GMarkAsPlayedData_response,
  GMarkAsPlayedReq,
  GMarkAsPlayedVars,
  GMarkAsViewedData,
  GMarkAsViewedData_response,
  GMarkAsViewedReq,
  GMarkAsViewedVars,
  GPostCommentData,
  GPostCommentData_response,
  GPostCommentData_response_data,
  GPostCommentReplyData,
  GPostCommentReplyData_response,
  GPostCommentReplyData_response_data,
  GPostCommentReplyReq,
  GPostCommentReplyVars,
  GPostCommentReq,
  GPostCommentVars,
  GPostDetailsData,
  GPostDetailsReq,
  GPostDetailsVars,
  GPostStatus,
  GPostVisibility,
  GUserVoicepodsData,
  GUserVoicepodsData_response,
  GUserVoicepodsData_response_data,
  GUserVoicepodsData_response_data_lastEvaluatedKey,
  GUserVoicepodsReq,
  GUserVoicepodsVars,
  GVPCommentData,
  GVPCommentReplyData,
  GVPCommentReplyReq,
  GVPCommentReplyVars,
  GVPCommentReq,
  GVPCommentVars,
  GVoiceEffectsData,
  GVoiceEffectsData_response,
  GVoiceEffectsData_response_data,
  GVoiceEffectsReq,
  GVoiceEffectsVars,
  GlastEvaluatedKeyForReplyComments,
  GlastEvaluatedKeyForVoicepodComments,
  GlastEvaluatedKeyForVoicepods,
])
final Serializers serializers = _serializersBuilder.build();
