targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: arre_base_gql|lib/src/schema.graphql
#          type_overrides:
#            Date:
#              name: DateTime
#            DateTime:
#              name: DateTime
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: arre_base_gql|lib/src/schema.graphql

#RUN dart run build_runner build