// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKJNhjj8Og1PaCkGL8ozEyRsPuxyaxRXA',
    appId: '1:577973200263:web:bb957cbb6b6ca39b175f22',
    messagingSenderId: '577973200263',
    projectId: 'arre-voice',
    authDomain: 'arre-voice.firebaseapp.com',
    storageBucket: 'arre-voice.appspot.com',
    measurementId: 'G-ENRRL5BHNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmyPzXbcOEguu6nvnAp2Tv09-jEaBG8TI',
    appId: '1:577973200263:android:794e0b73693bb52e175f22',
    messagingSenderId: '577973200263',
    projectId: 'arre-voice',
    storageBucket: 'arre-voice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZ1KLZ5WV__FBDzvgwjrTXo8lwMHv31c',
    appId: '1:577973200263:ios:b9d18b4342bece4b175f22',
    messagingSenderId: '577973200263',
    projectId: 'arre-voice',
    storageBucket: 'arre-voice.appspot.com',
    androidClientId: '577973200263-ppqg5og5hfgi0se2p9v3jgnpv36p1t88.apps.googleusercontent.com',
    iosClientId: '577973200263-72q2ed7jpfdo70sanlsmtemn4t0pl4mo.apps.googleusercontent.com',
    iosBundleId: 'com.arre.arrevoice',
  );
}
