targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: arre_explore_page_gql|lib/src/explore_page_schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: arre_explore_page_gql|lib/src/explore_page_schema.graphql

#RUN dart run build_runner build