name: arre_explore_page_gql
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  ferry: ^0.14.0+1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  ferry_generator: ^0.8.0+1
  build_runner: ^2.3.3
